services:
  app:
    build: ./
    ports:
      - "8080:${APP_PORT}"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  db:
    image: mysql:9
    ports:
      - "3306:${DB_PORT}"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      retries: 5